import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const source = await readFile(new URL("./zmath-auto.js", import.meta.url), "utf8");

assert.match(source, /\.mx_MessageComposer_sendMessage/);
assert.match(source, /addEventListener\("keydown"[\s\S]*true\)/);
assert.match(source, /addEventListener\("change"[\s\S]*true\)/);
assert.match(source, /room-upload-context-input/);
assert.match(source, /callchatZMathAuto/);
assert.match(source, /prepareFiles/);
assert.match(source, /prepareCallSecret/);
assert.match(source, /requireCallSecret/);
assert.match(source, /callchatZMathCallRequired/);
assert.match(source, /ZMATHCALL1/);
assert.match(source, /CallChat-ZMath-Media-Room-v1/);
assert.match(source, /preparedCallSecrets = new Map/);
assert.match(source, /Turn on automatic protection/);
assert.match(source, /Advanced options/);
assert.match(source, /Auto-unlock on this trusted device/);
assert.match(source, /restoreAutomaticSetup/);
assert.match(source, /previous automatic profile is unavailable/i);
assert.match(source, /setup\.hidden = matrixOnly/);
assert.match(source, /DEVICE_PROFILE_DOMAIN/);
assert.match(source, /indexedDB\.open/);
assert.match(source, /objectStore\(DEVICE_DB_STORE\)\.put\(record, TRUSTED_PROFILE_KEY\)/);
assert.match(source, /generateKey\([\s\S]*false,[\s\S]*\["encrypt", "decrypt"\]/);
assert.match(source, /MODULE_OWNER/);
assert.match(source, /Run encryption self-test/);
assert.match(source, /containerFingerprint/);
assert.match(source, /protectMessage/);
assert.match(source, /protectPayload/);
assert.match(source, /openMessage/);
assert.match(source, /openContainerPayload/);
assert.match(source, /MutationObserver/);
assert.match(source, /Matrix-only sending/);
assert.doesNotMatch(source, /localStorage\.setItem\([^\n]*ZMATHCALL1/);
assert.doesNotMatch(source, /localStorage\.setItem\([^\n]*passphrase/i);
assert.doesNotMatch(source, /localStorage\.setItem\(TRUSTED_PROFILE_KEY/);
assert.doesNotMatch(source, /openai|anthropic|gemini|ai api/i);

console.log("ZMath Auto Element interception contract: ok");
